version: '3'

services:

####################################
# Queue Container(s):
#
#   1. Redis Server Container
#              &&
#   2. Redis Dashboard Container
####################################
  redis:
    image: redis:5-alpine
    container_name: nauto-redis
  
  dashboard:
    build: ./project/dashboard
    image: redis-dashboard
    container_name: nauto-dashboard
    ports:
      - "9181:9181"
    command: rq-dashboard -H redis
    depends_on:
      - redis

####################################
# Server Container(s):
#
#   1. Python Flask Container
#              &&
#   2. Redis Worker Container(s)
####################################
  flask:
    build: .
    image: nauto-server
    container_name: nauto-flask
    ports:
      - "5000:5000"
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS=project.server.DockerDevConfig
    depends_on:
      - redis
  
  worker:
    image: nauto-server
    container_name: nauto-worker
    command: python manage.py run_worker
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS=project.server.DockerDevConfig
    depends_on:
      - redis

################################ Optionally
# Client Container(s):
#
#   1. React WebApp
################################
  react:
    build: ./project/client
    image: nauto-client
    container_name: nauto-react
    ports:
      - "80:3000"
    command: npm run start
    volumes:
      - ./project/client:/usr/src/app
    depends_on:
      - flask
