version: '3'

services:

################################################################
# Queue Container(s):
#
#   1. Redis Server Container
#              &&
#   2. Redis Dashboard Container
################################################################
  redis:
    container_name: nauto-redis
    image: redis:5-alpine
  
  dashboard:
    build: ./project/dashboard
    command: rq-dashboard -H redis
    container_name: nauto-dashboard
    depends_on:
      - redis
    image: redis-dashboard
    ports:
      - "9181:9181"

################################################################
# Server Container(s):
#
#   1. Python Flask Container
#              &&
#   2. Redis Worker Container(s)
################################################################
  flask:
    build: .
    command: python manage.py run -h 0.0.0.0
    container_name: nauto-flask
    depends_on:
      - redis
    environment:
      - APP_SETTINGS=project.server.DockerDevConfig
    image: nauto-server
    ports:
      - "5000:5000"
  
  worker:
    command: python manage.py run_worker
    container_name: nauto-worker
    depends_on:
      - redis
    environment:
      - APP_SETTINGS=project.server.DockerDevConfig
    image: nauto-server

# Optionally ###################################################
# Client Container(s):
#
#   1. React WebApp
################################################################
# Known Issue(s):
#
# https://github.com/facebook/create-react-app/issues/8688
#
################################################################
  react:
    build: ./project/client
    command: npm run start
    container_name: nauto-react
    depends_on:
      - flask
    image: nauto-client
    ports:
      - "80:3000"
    stdin_open: true
