version: '3'

services:

################################################################
# Queue Container(s):
#
#   1. Redis Server Container
#              &&
#   2. Redis Dashboard Container
################################################################
  redis:
    container_name: nauto-redis
    image: redis:5-alpine
  
  dashboard:
    build: ./project/dashboard
    command: rq-dashboard -H redis
    container_name: nauto-dashboard
    depends_on:
      - redis
    image: redis-dashboard
    ports:
      - "9181:9181"

################################################################
# Server Container(s):
#
#   1. Python Flask Container
#              &&
#   2. Redis Worker Container(s)
################################################################
  flask:
    build: .
    command: python manage.py run -h 0.0.0.0
    container_name: nauto-flask
    depends_on:
      - redis
    environment:
      - APP_SETTINGS=project.server.DockerDevConfig
    image: nauto-server
    ports:
      - "80:5000"
  
  worker:
    command: python manage.py run_worker
    container_name: nauto-worker
    depends_on:
      - redis
    environment:
      - APP_SETTINGS=project.server.DockerDevConfig
    image: nauto-server
