apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: nauto-server
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
