apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert -f docker-compose.yml
      --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
spec:
  replicas: 1
  selector:
    io.kompose.service: flask
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flask
    spec:
      containers:
      - args:
        - python
        - manage.py
        - run
        - -h
        - 0.0.0.0
        env:
        - name: APP_SETTINGS
          value: project.server.DockerDevConfig
        image: ' '
        name: nauto-flask
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nauto-flask
      from:
        kind: ImageStreamTag
        name: flask:latest
    type: ImageChange
status: {}
