apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert -f docker-compose.yml
      --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: react
  name: react
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  selector:
    io.kompose.service: react
status:
  loadBalancer: {}
