apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert -f docker-compose.yml
      --provider=openshift
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: react
  name: react
spec:
  replicas: 1
  selector:
    io.kompose.service: react
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: react
    spec:
      containers:
      - args:
        - npm
        - run
        - start
        image: ' '
        name: nauto-react
        ports:
        - containerPort: 3000
        resources: {}
        stdin: true
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nauto-react
      from:
        kind: ImageStreamTag
        name: react:latest
    type: ImageChange
status: {}
