apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: react
  name: react
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: nauto-client
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
