apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: redis:5-alpine
    generation: null
    importPolicy: {}
    name: 5-alpine
status:
  dockerImageRepository: ""
